services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    test.app\Repository\CircaDateRepository: '@App\Repository\CircaDateRepository'
    test.app\Repository\LinkRepository: '@App\Repository\LinkRepository'
    test.app\Repository\LocationRepository: '@App\Repository\LocationRepository'
    test.app\Repository\OccupationRepository: '@App\Repository\OccupationRepository'
    test.app\Repository\PersonRepository: '@App\Repository\PersonRepository'
    test.app\Repository\ReferenceRepository: '@App\Repository\ReferenceRepository'
    test.app\Repository\ReferenceRoleRepository: '@App\Repository\ReferenceRoleRepository'
